# syntax=docker/dockerfile:1
# Generated by DeepAgent. Rerunning the deploy regenerates this file — delete this line to keep your own edits.
# --- Build stage: all deps so the build (if any) can run ---
# --platform=linux/amd64 forces the same native binaries as the runtime,
# regardless of whether `docker build` runs on a Mac / arm laptop or on
# CI. Without it, a lockfile resolved on darwin-arm64 shipped darwin
# binaries into a linux/amd64 image and the pod crashed on boot loading
# a missing `.node` file (2026-09-29, team-wallet).
FROM --platform=linux/amd64 node:20-bookworm-slim AS builder
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 make g++ \
    && rm -rf /var/lib/apt/lists/*
COPY package*.json ./
RUN npm pkg delete scripts.prepare scripts.postinstall >/dev/null 2>&1 || true && unset NPM_CONFIG_OMIT && npm install --include=optional --no-audit --no-fund || npm install --include=optional --no-audit --no-fund --legacy-peer-deps
COPY . .
# The repo's own postinstall, now that the files it reads are here
# (no-op when the package.json defines none).
RUN npm run postinstall --if-present
# Prisma: generate the client BEFORE build (no-op without a schema).
RUN if [ -f prisma/schema.prisma ] || [ -f schema.prisma ]; then \
      npx --yes prisma generate; \
    fi
# Build-time env for the frontend build (added by DeepAgent).
# These are framework-prefixed, i.e. inlined into the public bundle by
# design — never put a credential in a build arg. The empty defaults keep
# the image buildable with no --build-arg; CI overrides them with the
# real values.
ARG NEXT_PUBLIC_PINATA_JWT=""
ENV NEXT_PUBLIC_PINATA_JWT=${NEXT_PUBLIC_PINATA_JWT}
ARG NEXT_PUBLIC_SOLANA_NETWORK=""
ENV NEXT_PUBLIC_SOLANA_NETWORK=${NEXT_PUBLIC_SOLANA_NETWORK}
ARG NEXT_PUBLIC_SOLANA_RPC_URL=""
ENV NEXT_PUBLIC_SOLANA_RPC_URL=${NEXT_PUBLIC_SOLANA_RPC_URL}
ARG NEXT_PUBLIC_TEAM_WALLET_PROGRAM_ID=""
ENV NEXT_PUBLIC_TEAM_WALLET_PROGRAM_ID=${NEXT_PUBLIC_TEAM_WALLET_PROGRAM_ID}
# Auto-build when the app defines a build script (Next.js needs it).
# Fails the image build if the script exists and errors — surfaces bugs early.
RUN if node -e "process.exit(require('./package.json').scripts?.build ? 0 : 1)"; then \
      npm run build; \
    else \
      echo "no build script — skipping"; \
    fi

# --- Runtime: non-root built-in `node` user ---
FROM --platform=linux/amd64 node:20-bookworm-slim AS runner
ENV NODE_ENV=production
# Caches must live on the ONE writable mount of a hardened pod. The deploy
# manifest runs this container with readOnlyRootFilesystem: true and a
# writable emptyDir at /tmp only (security-profile.ts, restricted profile).
# @swc/core ships its native binding compressed and decompresses it into a
# cache directory on first require — with HOME on the read-only layer that
# write is EROFS and Next dies loading next.config.ts (2026-09-29,
# team-wallet: 'SWC native addon: create cache root /home/node/.cache:
# Read-only file system', CrashLoopBackOff). XDG_CACHE_HOME moves every
# well-behaved cache to /tmp; SWC_NATIVE_BINDING_CACHE is swc's own
# explicit knob for the same path.
ENV XDG_CACHE_HOME=/tmp/.cache
ENV SWC_NATIVE_BINDING_CACHE=/tmp/.cache/swc-native
WORKDIR /app
# Copy the built app WITH its node_modules from the builder (avoids a second
# install and guarantees framework binaries + build output are present).
COPY --from=builder /app ./
# Numeric uid, not a name. Kubernetes' runAsNonRoot check refuses to start
# a container whose USER is a name: it cannot verify from outside the image
# that the name is non-root, and the pod dies with
# CreateContainerConfigError (2026-09).
# The node images ship 'node' as uid 1000.
USER 1000
EXPOSE 3000
# HEALTHCHECK proves the server is actually listening on its declared port
# BEFORE k8s pulls the image. If the process dies at boot (missing native
# binary, uncaught exception, wrong entrypoint), the local `docker run`
# and the CI smoke step both see UNHEALTHY within seconds and refuse to
# push — the entire "compiles, pushes, CrashLoopBackOff" class stops at
# build time. Uses `node -e` because bookworm-slim ships no curl/wget.
# statusCode < 500 accepts any response the app produces (200, 404,
# 302 …) — the point is "the process answers TCP + HTTP", not that a
# specific route returns 200. That route check belongs to the K8s
# readiness probe, which asks the app-defined path.
HEALTHCHECK --interval=15s --timeout=5s --start-period=20s --retries=3 \
    CMD node -e "require('http').get('http://127.0.0.1:3000/', r => process.exit(r.statusCode < 500 ? 0 : 1)).on('error', () => process.exit(1))"
CMD ["sh", "-c", "export PATH=/app/node_modules/.bin:$PATH; exec next start"]
