# syntax=docker/dockerfile:1
# Generated by DeepAgent. Rerunning the deploy regenerates this file — delete this line to keep your own edits.
# --- Build stage: all deps so the build (if any) can run ---
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm pkg delete scripts.prepare >/dev/null 2>&1 || true && if [ -f package-lock.json ]; then npm ci || npm ci --legacy-peer-deps; else npm install; fi
COPY . .
# Prisma: generate the client BEFORE build (no-op without a schema).
RUN if [ -f prisma/schema.prisma ] || [ -f schema.prisma ]; then \
      npx --yes prisma generate; \
    fi
# Auto-build when the app defines a build script (Next.js needs it).
# Fails the image build if the script exists and errors — surfaces bugs early.
RUN if node -e "process.exit(require('./package.json').scripts?.build ? 0 : 1)"; then \
      npm run build; \
    else \
      echo "no build script — skipping"; \
    fi

# --- Runtime: non-root built-in `node` user ---
FROM node:20-alpine AS runner
ENV NODE_ENV=production
WORKDIR /app
# Copy the built app WITH its node_modules from the builder (avoids a second
# install and guarantees framework binaries + build output are present).
COPY --from=builder /app ./
# Numeric uid, not a name. Kubernetes' runAsNonRoot check refuses to start
# a container whose USER is a name: it cannot verify from outside the image
# that the name is non-root, and the pod dies with
# CreateContainerConfigError (2026-09).
# The node images ship 'node' as uid 1000.
USER 1000
EXPOSE 3000
CMD ["sh", "-c", "export PATH=/app/node_modules/.bin:$PATH; exec next start"]
