apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: team-wallet-aws-secret-access-key
  namespace: den
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: teams-dev/den/AWS_SECRET_ACCESS_KEY
